services:
    sveltekit:
        build: .
        container_name: account-frontend
        ports:
            - "2000:3000"
        restart: unless-stopped
        environment:
            VITE_COMMIT_HASH: ${VITE_COMMIT_HASH}
            VITE_COMMIT_URL: ${VITE_COMMIT_URL}