services:
    sveltekit:
        build: .
        container_name: account-frontend
        ports:
            - "2000:3000"
        restart: unless-stopped
        env_file:
            - .env.version